# Generated by Django 5.0.6 on 2025-07-09 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField()),
                ('available_seats', models.PositiveSmallIntegerField()),
                ('table_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cleaning', 'Cleaning'), ('unavailable', 'Unavailable'), ('reserved', 'Reserved')], default='available', max_length=11)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'table',
            },
        ),
    ]
