# Generated by Django 5.0.6 on 2025-07-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount for this table.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='min_seats',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum number of seats that can be accommodated at this table with at least minimum order.'),
        ),
    ]
