# Generated by Django 4.2.23 on 2025-07-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_tablemodel_min_order_tablemodel_min_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemodel',
            old_name='min_seats',
            new_name='condition_seats',
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='min_order',
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='condition_order',
            field=models.PositiveSmallIntegerField(default=0.0, help_text='Minimum order amount for this table.'),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='available_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='booked_seats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
